### ISSUE TITLE
Password reset codes should be invalidated when used

### ISSUE THREAD

**Issue by obar** [celiao/django-rest-authemail#2]
Current behavior: the same password reset code can be used repeatedly.
Suggested behavior: a reset code is deleted after successful use.

Ideally: a reset code will expire after some configurable length of time.

**Comment by andreyshipilov** [comment]
Have to second that. Right after the password was changed, the code should be removed.

**Comment by sibis** [comment]
@andreyshipilov I will take it further in that flow. and give pull request once it is done

**Comment by celiao** [comment]
This issue is addressed by these three approaches:
1. Password reset codes are deleted immediately after use.  Commit 83af1b6f1042634cd0f2d028885c924dcf354a85.
1. When a user requests a new password reset code, all unused password reset codes for that user are deleted.  Commit 8be01a2ddd32652ac0342f6b954ac6457c3c8bb3.
1. If a user tries to use a password reset code that is older than the expiry period (currently 3 days), the password reset code is deleted and verification fails.  Commit acd13ced5b4e8789995eeb9dd150baed98ec47f1.

By combining these three approaches, each user can have at most one outstanding unused possibly-expired password reset code, so the need for a cron job to clean out expired password reset codes is avoided.
