### ISSUE TITLE
An API endpoint to change user info

### ISSUE THREAD

**Issue by ghost** [celiao/django-rest-authemail#4]
An API endpoint to change user info. Possibly a POST to /api/accounts/users/me. Or maybe documentation on how to implement one since most user info are app specific. I'm new to Django and is still learning about Django Rest Framework and has no clue how to go about doing it.

**Comment by celiao** [comment]
Since user information is application-specific, providing an API endpoint and front end for changing a user's information is an exercise for the application programmer.

In the interest of showing how such an implementation could work,  I added an API endpoint and super-basic front end to change user information to the Example Project.  Follow the steps in the README to install the Example Project and play with the interface to change a user's information.

Here are the key pieces of the Users Me Change functionality:
```
example_project/accounts/
    serializers.py
        class MyUserChangeSerializer(serializers.ModelSerializer):
            ...
    urls.py
        ...
        path('users/me/change/', views.MyUserMeChange.as_view()),
        ...
    views.py
        class MyUserMeChange(APIView):
            ...

example_project/example_project/
    templates/
        users_me_change.html
        users_me_change_success.html
    forms.py
        class UsersMeChangeForm(AddErrorMixin, forms.Form):
            ...
    urls.py
            ...
            path('users/me/change/', views.UsersMeChangeView.as_view(), name='users_me_change_page'),
            path('users/me/change/success/', views.UsersMeChangeSuccessView.as_view(), name='users_me_change_success'),
            ...
    views.py
        class UsersMeChangeView(FormView):
            ...
        class UsersMeChangeSuccessView(TemplateView):
            ...
    wrapperplus.py (new)
        class AuthemailPlus(wrapper.Authemail):
            ...
            def users_me_change(self, **kwargs):
            ...

```
